// <auto-generated>
//   Gerado manualmente para uso com LocalizableResourceString do Roslyn.
//   Atualizar junto com Resources.resx e Resources.pt-BR.resx ao adicionar novas regras.
// </auto-generated>

#nullable enable

using System.Globalization;
using System.Resources;

namespace RuntimeSentinel.Analyzers;

internal static class Resources
{
    private static ResourceManager? s_resourceManager;

    /// <summary>
    /// ResourceManager que resolve strings pelo idioma da cultura atual da UI.
    /// Em ambiente PT-BR, carrega Resources.pt-BR.resx via satellite assembly.
    /// Em ambiente EN (ou qualquer outro), carrega Resources.resx (fallback neutro).
    /// </summary>
    internal static ResourceManager ResourceManager =>
        s_resourceManager ??= new ResourceManager(
            "RuntimeSentinel.Analyzers.Resources",
            typeof(Resources).Assembly);

    /// <summary>
    /// Cultura explícita para testes. Null = usa CultureInfo.CurrentUICulture.
    /// </summary>
    internal static CultureInfo? Culture { get; set; }

    // -------------------------------------------------------------------------
    // RS1001 - Thread.Sleep em método async
    // -------------------------------------------------------------------------

    internal static string RS1001_Title
        => ResourceManager.GetString(nameof(RS1001_Title), Culture)
           ?? "Thread.Sleep detected inside async method";

    internal static string RS1001_MessageFormat
        => ResourceManager.GetString(nameof(RS1001_MessageFormat), Culture)
           ?? "Hold on! Thread.Sleep() is blocking a real thread inside an async method. Under load, this starves the thread pool. Swap it for 'await Task.Delay()'.";

    internal static string RS1001_Description
        => ResourceManager.GetString(nameof(RS1001_Description), Culture)
           ?? "Thread.Sleep blocks the calling thread completely. Inside an async method this defeats async/await and can cause thread pool starvation under high load.";

    // -------------------------------------------------------------------------
    // RS1002 - Task.WhenAll sem limite explícito
    // -------------------------------------------------------------------------

    internal static string RS1002_Title
        => ResourceManager.GetString(nameof(RS1002_Title), Culture)
           ?? "Task.WhenAll fan-out may be unbounded";

    internal static string RS1002_MessageFormat
        => ResourceManager.GetString(nameof(RS1002_MessageFormat), Culture)
           ?? "Heads up! Task.WhenAll is processing a Select() projection without an explicit limit.";

    internal static string RS1002_Description
        => ResourceManager.GetString(nameof(RS1002_Description), Culture)
           ?? "Task.WhenAll over an unbounded Select projection can trigger too many concurrent operations at once.";

    // -------------------------------------------------------------------------
    // RS1003 - Parallel.ForEach sem limite explícito
    // -------------------------------------------------------------------------

    internal static string RS1003_Title
        => ResourceManager.GetString(nameof(RS1003_Title), Culture)
           ?? "Parallel.ForEach may run without an explicit concurrency limit";

    internal static string RS1003_MessageFormat
        => ResourceManager.GetString(nameof(RS1003_MessageFormat), Culture)
           ?? "Careful! Parallel.ForEach is running without ParallelOptions/MaxDegreeOfParallelism.";

    internal static string RS1003_Description
        => ResourceManager.GetString(nameof(RS1003_Description), Culture)
           ?? "Using Parallel.ForEach without an explicit MaxDegreeOfParallelism may oversubscribe resources.";

    // -------------------------------------------------------------------------
    // RS1004 - Bloqueio com Task.Wait / Task.Result
    // -------------------------------------------------------------------------

    internal static string RS1004_Title
        => ResourceManager.GetString(nameof(RS1004_Title), Culture)
           ?? "Blocking async flow with Task.Wait/Result";

    internal static string RS1004_MessageFormat
        => ResourceManager.GetString(nameof(RS1004_MessageFormat), Culture)
           ?? "Yikes! Blocking on Task via .Wait() or .Result can starve threads.";

    internal static string RS1004_Description
        => ResourceManager.GetString(nameof(RS1004_Description), Culture)
           ?? "Calling Task.Wait() or reading Task.Result blocks the current thread.";

    // -------------------------------------------------------------------------
    // RS1005 - Materialização prematura com ToList
    // -------------------------------------------------------------------------

    internal static string RS1005_Title
        => ResourceManager.GetString(nameof(RS1005_Title), Culture)
           ?? "Potentially heavy ToList() materialization";

    internal static string RS1005_MessageFormat
        => ResourceManager.GetString(nameof(RS1005_MessageFormat), Culture)
           ?? "Heads up! This LINQ pipeline is being materialized with ToList() without an explicit Take(...) limit.";

    internal static string RS1005_Description
        => ResourceManager.GetString(nameof(RS1005_Description), Culture)
           ?? "Materializing a LINQ pipeline with ToList() too early or without bounds can increase memory pressure.";

    // -------------------------------------------------------------------------
    // RS1006 - HttpClient instanciado em escopo de metodo
    // -------------------------------------------------------------------------

    internal static string RS1006_Title
        => ResourceManager.GetString(nameof(RS1006_Title), Culture)
           ?? "HttpClient instantiated inside method scope";

    internal static string RS1006_MessageFormat
        => ResourceManager.GetString(nameof(RS1006_MessageFormat), Culture)
           ?? "Heads up! Creating HttpClient inside a method can lead to socket exhaustion and slower communication under load.";

    internal static string RS1006_Description
        => ResourceManager.GetString(nameof(RS1006_Description), Culture)
           ?? "Instantiating HttpClient per operation may create excessive socket churn and connection pressure.";

    // -------------------------------------------------------------------------
    // RS1007 - Chamada HTTP sem timeout explicito
    // -------------------------------------------------------------------------

    internal static string RS1007_Title
        => ResourceManager.GetString(nameof(RS1007_Title), Culture)
           ?? "HTTP call without explicit timeout policy";

    internal static string RS1007_MessageFormat
        => ResourceManager.GetString(nameof(RS1007_MessageFormat), Culture)
           ?? "Heads up! This HttpClient call has no explicit timeout (Timeout property or CancellationToken).";

    internal static string RS1007_Description
        => ResourceManager.GetString(nameof(RS1007_Description), Culture)
           ?? "HTTP communication should define explicit timeout boundaries to avoid stuck calls and cascading latency.";

    // -------------------------------------------------------------------------
    // RS1008 - Retry sem limite explicito de tentativas
    // -------------------------------------------------------------------------

    internal static string RS1008_Title
        => ResourceManager.GetString(nameof(RS1008_Title), Culture)
           ?? "Retry loop without explicit max attempts";

    internal static string RS1008_MessageFormat
        => ResourceManager.GetString(nameof(RS1008_MessageFormat), Culture)
           ?? "Careful! This retry loop appears unbounded (infinite condition without explicit exit).";

    internal static string RS1008_Description
        => ResourceManager.GetString(nameof(RS1008_Description), Culture)
           ?? "Unbounded retries can create feedback loops against unstable dependencies.";

    // -------------------------------------------------------------------------
    // RS1009 - Retry sem backoff exponencial
    // -------------------------------------------------------------------------

    internal static string RS1009_Title
        => ResourceManager.GetString(nameof(RS1009_Title), Culture)
           ?? "Retry policy without exponential backoff";

    internal static string RS1009_MessageFormat
        => ResourceManager.GetString(nameof(RS1009_MessageFormat), Culture)
           ?? "Heads up! Retry in HTTP path appears to use fixed delay.";

    internal static string RS1009_Description
        => ResourceManager.GetString(nameof(RS1009_Description), Culture)
           ?? "Using fixed delay in retries can keep hammering a failing dependency at high frequency.";

    // -------------------------------------------------------------------------
    // RS1010 - Retry sem jitter
    // -------------------------------------------------------------------------

    internal static string RS1010_Title
        => ResourceManager.GetString(nameof(RS1010_Title), Culture)
           ?? "Retry policy without jitter";

    internal static string RS1010_MessageFormat
        => ResourceManager.GetString(nameof(RS1010_MessageFormat), Culture)
           ?? "Heads up! Retry appears exponential but without jitter.";

    internal static string RS1010_Description
        => ResourceManager.GetString(nameof(RS1010_Description), Culture)
           ?? "Exponential backoff without jitter can synchronize retries across instances.";
}
